[package]
name = "exercise"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.75"
futures = "0.3.29"
reqwest = "0.11.22"
tokio = { version = "1.34.0", features = ["net", "full"] }
